### ISSUE TITLE
Ajout possibilité d'activer la notification d'alarme

### ISSUE THREAD

**Issue by echaplet** [Famille-OZAER/jeezviz#2]
Bonjour,

j'ai testé votre plugin sur Jeedom avec ma caméra EZVIZ et ça fonctionne bien.
J'ai essayé l'activation/désactivation du mode privé, mais je souhaiterai pouvoir activer/désactiver la notification d'alarme via Jeedom.
J'ai vu que la fonction est déja prévue dans le code, est-ce possible de l'ajouter au niveau des commandes du plugin jeedom ?

Merci à vous !
Eric

**Comment by benmac12** [comment]
Bonjour, également intéressé par l'implémentation du sleep mode, et également de l'activation de la notification d'alarme. Ca serait vraiment top, il ne manque plus que ça pour avoir une intégration entière sous jeedom.
Merci également pour ce qui à déjà été réalisé.
Benjamin

**Comment by OOZAER** [comment]
Bonjour,

Je n'ai mal heureusement pas de temps à consacrer sur le plugin.
Cependant, je veux bien donner des droits pour que vous puissiez proposer des corrections.

Olivier

**Comment by echaplet** [comment]
Bonjour, je veux bien, merci !

D'autre part, avez vous des conseils pour savoir quels sont les logiciels
nécessaires pour développer un plugin jeedom sous windows ? Il y a beaucoup
d'informations sous linux, mais très peu sous windows.

Merci à vous
Eric

**Comment by OOZAER** [comment]
Bonjour,

Je viens de vous ajouter, dites moi si vous pouvez proposer une modif de code.

Cordialement
Olivier

**Comment by OOZAER** [comment]
> Bonjour, également intéressé par l'implémentation du sleep mode, et également de l'activation de la notification d'alarme. Ca serait vraiment top, il ne manque plus que ça pour avoir une intégration entière sous jeedom. Merci également pour ce qui à déjà été réalisé. Benjamin

Bonjour,

J'ai ouvert une issue dédiée pour le mode sleep

**Comment by OOZAER** [comment]
Bonjour (enfin re :)),

J'ai creusé le sujet mais je ne parviens pas à faire activer ou désactiver les notifications.
La fonction permettant de modifier le type de notification fonctionne mais pas le fait d'activer ou non.

Je me base sur le projet pyezviz pour obtenir les points d'entrées des api mais dans le cas des notifications, il semble que ce soit directement un appel soap mais je ne comprends pas le code.

Si quelqu'un sait traduire la fonction en php, ce serait top :)

**Comment by OOZAER** [comment]
Bonjour,

La fonction Sleep Mode et Notification d'alarme a été implémenté dans la nouvelle version du plugin [Jeezviz V2](https://github.com/Famille-OZAER/jeezvizv2)

Il y a également pas mal d'autres ajouts.

A titre indicatif, j'ai complètement changé de stratégie : au lieu de réécrire quelque chose d'existant, j'ai ajouté l'api [pyEzviz](https://github.com/BaQs/pyEzviz) (en python) en tant que dépendance à mon plugin et j'appelle l'api via PHP.

Ce cette manière si des évolutions sont apporté à l'API de [BaQs](https://github.com/BaQs) il me sera beaucoup plus facile de les intégrer dans le plugin Jeedom.

@echaplet : Je m'aperçoit que je n'ai pas répondu à ta question.
Personnellement, j'utilise Visual Studio Code qui me convient parfaitement.
Cependant, je ne peux pas tester directement sur ma machine (Windows) du coup, je publie mes modifs via l'explorateur Jeedom et je teste.

Cordialement

Olivier

**Comment by OOZAER** [comment]
Bonjour,

La fonction a été implémenté dans la nouvelle version du plugin [Jeezviz V2](https://github.com/Famille-OZAER/jeezvizv2)

Cordialement

Olivier
